version: '1.1'

services:

  # ────────────────────────────────────────────────
  #                Prometheus
  # ────────────────────────────────────────────────
  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'      # Adjust retention period
      - '--storage.tsdb.wal-compression'         # Compress write-ahead log
      - '--web.enable-lifecycle'                 # Enable runtime reloading
    ports:
      - "9290:9090"
    networks:
      - monitoring-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"

  # ────────────────────────────────────────────────
  #              Cadvisor
  # ────────────────────────────────────────────────
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8280:8080"
    networks:
      - monitoring-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"

  # ────────────────────────────────────────────────
  #                   Grafana
  # ────────────────────────────────────────────────
  grafana:
    image: grafana/grafana:12.4.0-21342258703
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - "3200:3000"
    networks:
      - monitoring-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"

  # ────────────────────────────────────────────────
  #                   Langfuse
  # ────────────────────────────────────────────────

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring-net:
    driver: bridge